name: Build
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf setup
        uses: asdf-vm/actions/setup@v1.0.0

      - name: asdf chezscheme install
        run: |
          asdf plugin-add chezscheme https://github.com/asdf-community/asdf-chezscheme.git
          asdf install chezscheme latest
          asdf local chezscheme latest

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: idris2 --help
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
